### ISSUE TITLE
 About the loss function

### ISSUE THREAD

**Issue by WdBlink** [google-research/augmix#1]
Hello, I have read your paper and it's really impressive work. I also have a question about the loss function when I read the AUGMIX Pseudocode part.  The question is why you didn't use the x_{augmix1} and x_{augmix2} as the input of the loss function L? It seems that you did not use data augmentation when training the model, augmix_data only works in the regularization term of Jensen-Shannon.

**Comment by hendrycks** [comment]
Classifying only clean data tended to slightly improve accuracy.
