### ISSUE TITLE
A question in "third_party/WideResNet_pytorch/wideresnet.py      out = self.relu2(self.bn2(self.conv1(out)))

### ISSUE THREAD

**Issue by longlongvip** [google-research/augmix#12]
The **42nd** row in the code :  **out = self.relu2(self.bn2(self.conv1(out)))**, is it supposed to be **out = self.relu2(self.bn2(self.conv1(x)))**?

**Comment by hendrycks** [comment]
I have not trained any models with your proposed change to this third party code, but that might be better and should probably work.

**Comment by longlongvip** [comment]
Thank you!I know it
