### ISSUE TITLE
`depth` is constant each `width`

### ISSUE THREAD

**Issue by yumion** [google-research/augmix#13]
Hello, thank you for releasing a implementation.

In my understanding, we change number of `op` as `depth` each `width` , however this code should be same `depth` each `width`  here.
https://github.com/google-research/augmix/blob/7c84885fe064435b4b7a8b596b937f0a879e458c/augment_and_mix.py#L61

So,  we change code like below, right?
```
depth = np.random.randint(1, depth + 1 if depth > 0 else 4)
```

Best, regard.

**Comment by normster** [comment]
Thanks for pointing this out, you're completely right. Feel free to submit a PR or I can make the change when I get a chance.

**Comment by normster** [comment]
Hi @yumion, I took a closer look and the suggested fix doesn't address the bug of overwriting `depth` on the first branch.
