### ISSUE TITLE
What about the performance on regular classification problems?

### ISSUE THREAD

**Issue by JiyueWang** [google-research/augmix#16]
Can Augmix boost training on regular classification problems as Mixup or Cutmix do?

**Comment by hendrycks** [comment]
In the paper the IID accuracy can increase for a ResNet-50. The more aggressive the augmentation, the higher capacity the model must be. A paper showing that AugMix+other augmentations can help high-capacity ResNeXts is this: https://arxiv.org/pdf/2006.16241.pdf#page=7&zoom=100,424,618

**Comment by yechenzhi** [comment]
Does the model's uncertainty estimate correlate to the model's OOD detection ability? Are they the same thing?

**Comment by hendrycks** [comment]
No, calibration on in-class data is often decoupled from good uncertainty
estimation on out-of-class data.

**Comment by zjysteven** [comment]
@hendrycks Just curious, is there any evidence for your last comment about calibration on in- and out-class data? I haven't really seen people talking about these two together.

**Comment by hendrycks** [comment]
Consider the rightmost two columns of this paper: https://arxiv.org/pdf/2003.03879.pdf#page=3&zoom=100,0,0
I don't see a clear association between Expected Calibration Error and OOD Detection Error.
