### ISSUE TITLE
KL divergenve

### ISSUE THREAD

**Issue by MADONOKOUKI** [google-research/augmix#17]
https://github.com/google-research/augmix/blob/9b9824c7c19bf7e72df2d085d97b99b3bfb00ba4/cifar.py#L233

Hi. 
KL divergence is indeed asymmetry distribution.
The code looks to minimize the mixture of distribution to p_original, p_aug1, p_aug2

**Comment by hendrycks** [comment]
The Jensen-Shannon Divergence is symmetric and can be written in terms of KL Divergences.
