### ISSUE TITLE
Issue loading pretrained weights

### ISSUE THREAD

**Issue by humzaiqbal** [google-research/augmix#18]
When I download the `checkpoint.pth.tar` file for the pretrained ImageNet model I get the error
`tar: Error opening archive: Unrecognized archive format`, would it be possible to release the weights in another format (like a zip perhaps?) Unfortunately I don't have access to the ImageNet dataset so I can't retrain it myself

**Comment by hendrycks** [comment]
Just try loading the checkpoint file directly without untarring.

**Comment by humzaiqbal** [comment]
Great thanks that worked :)

**Comment by normster** [comment]
i went to college with this guy lol
