### ISSUE TITLE
I found an error

### ISSUE THREAD

**Issue by minjieharmo** [google-research/augmix#2]

**Comment by minjieharmo** [comment]
If depth=-1, augmix will generate same depths as (1,1,1) ,(2,2,2) or (3,3,3).
from 61 line of augment_and_mix.py
    depth = depth if depth > 0 else np.random.randint(1, 4)
    for _ in range(depth):
should be
    a = depth if depth > 0 else np.random.randint(1, 4)
    for _ in range(a):

**Comment by normster** [comment]
Thanks for finding this! I thought I had fixed this but I must have dropped the commit somehow. I will fix this but for now please see the analogous section in [cifar.py](https://github.com/google-research/augmix/blob/master/cifar.py#L163) for the correct depth.
