### ISSUE TITLE
Little difference between with/without JSD loss

### ISSUE THREAD

**Issue by xiangyu19** [google-research/augmix#6]
Thanks for your impressive contribution so much. I have one question when training this model.
When I set the no_jsd to True/False (cifar 100) using python cifar.py to get table 4, I got a 36.073(published 39.8) for no_jsd=True and 35.895(published 35.9). Do you have any idea why I got such a huge difference when setting the no_jsd to True?

**Comment by hendrycks** [comment]
It may be noise; I should say we did not run with the exact code used in this repository, but it should be representative enough. I expect that the perturbation stability and calibration is quite improved by the JSD loss. If you found it didn't help with corrupution robustness, perturbation stability, or calibration on CIFAR-10 and CIFAR-100, then there is a bug. If you suspect a bug let us know.
