### ISSUE TITLE
Can you share any acc information per epoch?

### ISSUE THREAD

**Issue by seominseok0429** [google-research/augmix#7]
Hi Author I am a college student studying deep learning in Korea. I read your paper very interesting. But I am running AugMix on imagenet and I have to wait 6 days with my GPU machine. So I'm wondering if learning is going well. To find out the trend in the middle, can you share any acc information per epoch?

**Comment by hendrycks** [comment]
Here's the training log of a model that trained for 90 epochs.
https://drive.google.com/file/d/1CGHCaK-ol6UjVsBFo-87m18WA6sq25qJ/view?usp=sharing

**Comment by seominseok0429** [comment]
Thank you for your kind reply. Do you ever get a lot of performance instability in the early stages of learning?

**Comment by hendrycks** [comment]
No. Do you have better luck with this code? https://github.com/google-research/augmix/issues/3#issuecomment-569455385
If so, that that suggests the main code might have an issue, but the code I linked to I have certainly used without instability.
